language: node_js
node_js:
  - 14

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version  # prints the version of logging
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user abheist/udagram-api-user

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abheist/udagram-api-user